apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: automationrepository.azurecr.io/frontend-image
          ports:
            - containerPort: 8080
          env:
          - name: ZIPKIN_URL
            value: "http://zipkin:9411/api/v2/spans"