# 📦 ci.yml - Lint, tests, SonarQube, Trivy
name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-test-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: '.'

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: automationrepository.azurecr.io/frontend-image:latest
