 # 📬 notify.yml - Slack notification
name: Slack Notification

on:
  workflow_run:
    workflows: ["CD Pipeline", "Security Scan"]
    types:
      - completed

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: '#36a64f'
          SLACK_MESSAGE: '🚀 Nuevo despliegue o escaneo de seguridad completado en AKS para frontend.'